### ISSUE TITLE
Discovering roles hierarchy

### ISSUE THREAD

**Issue by igorcadelima** [moise-lang/moise#10]
Hi, @jomifred 

I wonder if there's currently a way for an agent to find out if another is playing any extension of a certain role. For example, let's say we have two agents, `bob` and `alice`, and three roles have been defined, `ra`, `rb`, and `rc`. `rc` extends `rb`, which extends `ra`. `bob` is playing `rc` and `alice` is playing `ra`. How could `alice` find an agent that also plays `ra` or any extension of it without asking anyone? 

I know the Normative Board stores facts like:
```
play(alice,ra,team)
play(bob,rc,team)
subrole(rc,rb)[source(np)]
subrole(rb,ra)[source(np)]
subrole(ra,soc)[source(np)]
```
but they're not observable by the agents. 

If there's currently no way to find the agents which are playing `ra` or extensions of it, maybe the facts above could be observable properties of OrgBoard? Just a thought.

Cheers.

**Comment by jomifred** [comment]
Hi Igor,

your agents should focus on the GroupBoard (where roles are managed). Besides who plays what, there is an obs. prop. with all the OS (organisational specification) in prolog format. You can search in this spec which are the subroles and, by play/3 who are those agents.

I guess the prolog rule for that is quite complex… but feasible. 

HTH,

-- 
Jomi Fred Hubner
Federal University of Santa Catarina
Department of Automation and Systems Engineering
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br

**Comment by igorcadelima** [comment]
Hi, Jomi.

Yes, you're totally right! I was actually executing an extension of Moise's organisational artefacts which wasn't getting the org spec correctly. Sorry about that!

**Comment by igorcadelima** [comment]
Actually, the extension is working exactly as Moise's default behaviour for this matter. The problem was that, one more time, to simplify the problem, I ended up changing the scenario by mistake (I gotta be more careful with this). 

In my actual scenario, `alice` plays a role equivalent to `rb` in the hierarchy I mentioned, instead of `ra`, and my structural spec is like
```
<structural-specification>
  <role-definitions>
    <role id="ra" />
    <role id="rb">
      <extends role="ra" />
    </role>
    <role id="rc">
      <extends role="rb" />
    </role>
  </role-definitions>
  <group-specification id="group1">
    <roles>
        <role id="rb" min="1" max="1"/>
        <role id="rc" min="1" max="1"/>
    </roles>
  </group-specification>
</structural-specification>
```
With this configuration I get the following observable property:

> specification(group_specification(group1,**[role(rb,[rc],1,1,[],[]),role(rc,[],1,1,[],[])]**,[],properties([])))[artifact_id(cobj_4),percept_type(obs_prop),source(percept),artifact_name(cobj_4,team),workspace(cobj_4,org,cobj_2)].

Notice that in this case I can't know which roles extend `ra`. Is this the expected behaviour?

Thanks in advance!

**Comment by jomifred** [comment]
Right, the spec includes only sub-roles, not super-roles. I’ll fix that.

> On 14 de ago de 2017, at 01:46, Igor C. A. de Lima <notifications@github.com> wrote:
> 
> Actually, the extension is working exactly as Moise's default behaviour for this matter. The problem was that, one more time, to simplify the problem, I ended up changing the scenario by mistake (I gotta be more careful with this).
> 
> In my actual scenario, alice plays a role equivalent to rb in the hierarchy I mentioned, instead of ra, and my structural spec is like
> 
> <structural-specification>
>   <role-definitions>
>     <role id="ra" />
>     <role id="rb">
>       <extends role="ra" />
>     </role>
>     <role id="rc">
>       <extends role="rb" />
>     </role>
>   </role-definitions>
>   <group-specification id="group1">
>     <roles>
>         <role id="rb" min="1" max="1"/>
>         <role id="rc" min="1" max="1"/>
>     </roles>
>   </group-specification>
> </structural-specification>
> 
> With this configuration I get the following observable property:
> 
> specification(group_specification(group1,[role(rb,[rc],1,1,[],[]),role(rc,[],1,1,[],[])],[],properties([])))[artifact_id(cobj_4),percept_type(obs_prop),source(percept),artifact_name(cobj_4,team),workspace(cobj_4,org,cobj_2)].
> 
> Notice that in this case I can't know which roles extend ra. Is this the expected behaviour?
> 
> Thanks in advance!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by jomifred** [comment]
done.

> On 14 de ago de 2017, at 08:16, Jomi Hubner <jomifred@gmail.com> wrote:
> 
> Right, the spec includes only sub-roles, not super-roles. I’ll fix that.
> 
>> On 14 de ago de 2017, at 01:46, Igor C. A. de Lima <notifications@github.com> wrote:
>> 
>> Actually, the extension is working exactly as Moise's default behaviour for this matter. The problem was that, one more time, to simplify the problem, I ended up changing the scenario by mistake (I gotta be more careful with this).
>> 
>> In my actual scenario, alice plays a role equivalent to rb in the hierarchy I mentioned, instead of ra, and my structural spec is like
>> 
>> <structural-specification>
>>  <role-definitions>
>>    <role id="ra" />
>>    <role id="rb">
>>      <extends role="ra" />
>>    </role>
>>    <role id="rc">
>>      <extends role="rb" />
>>    </role>
>>  </role-definitions>
>>  <group-specification id="group1">
>>    <roles>
>>        <role id="rb" min="1" max="1"/>
>>        <role id="rc" min="1" max="1"/>
>>    </roles>
>>  </group-specification>
>> </structural-specification>
>> 
>> With this configuration I get the following observable property:
>> 
>> specification(group_specification(group1,[role(rb,[rc],1,1,[],[]),role(rc,[],1,1,[],[])],[],properties([])))[artifact_id(cobj_4),percept_type(obs_prop),source(percept),artifact_name(cobj_4,team),workspace(cobj_4,org,cobj_2)].
>> 
>> Notice that in this case I can't know which roles extend ra. Is this the expected behaviour?
>> 
>> Thanks in advance!
>> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> -- 
> Jomi Fred Hubner
> Department of Automation and Systems Engineering
> Federal University of Santa Catarina
> PO Box 476, Florianópolis, SC
> 88040-900 Brazil
> http://jomi.das.ufsc.br
> -- 
> be good. be kind. be happy. (Conrad Anker)

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by igorcadelima** [comment]
Thanks heaps, Jomi!
